services:
  web:
    build: .
    environment:
      - DEBUG_MODE=${DEBUG}
    depends_on:
      - redis
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:5000/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - /Volumes/Macintosh HD/Users/borysmenko/Desktop/share:/app/volum
    networks:
      - mynetwork
  redis:
    image: "redis"
    container_name: redis
    hostname: redis
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - mynetwork
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "127.0.0.1:8081:8081"
    networks:
      - mynetwork
networks:
  mynetwork:
