apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.pod.name }}
spec:
  type: NodePort
  selector:
    app: my-k8s
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 5000
      targetPort: 5000
      name: hello
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30084
    - port: 6379
      targetPort: 6379
      name: hello1
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30082
    - port: 8081
      targetPort: 8081
      name: hello2
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30083