apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.pod.vault }}
  labels: 
    app: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - name: vault
        image: {{ .Values.images.vault }}
        args: ["server", "-dev", "-dev-root-token-id=root"]
        ports:
        - containerPort: 8200
