apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.pod.vault }}
spec:
  type: NodePort
  selector:
    app: vault
  ports:
  - protocol: TCP
    port: 8200
    targetPort: 8200
    nodePort: 30090
    name: vault-port
---

apiVersion: v1
kind: Service
metadata:
  name: vault
  labels:
    app: vault
spec:
  ports:
    - name: vault
      port: 8200
  selector:
    app: vault
      
